name: integration test all
on: pull_request
jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            go:
              - '**/*.go'
              - '**/*.gotpl'
              - '**/*.mod'
              - '**/*.sum'
              - '**/*.work'

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: integration
        if: steps.changes.outputs.go == 'true'
        run: docker build . -f test/integration/integration.dockerfile -t integration && docker run integration
