name: integration test all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: integration
        run: bash .github/workflows/integration.sh
