name: integration test all
on: pull_request
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go integration-test.yml"

jobs:
  integration:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: integration
        run: docker build . --platform linux/amd64 -f test/integration/integration.dockerfile -t integration && docker run --platform linux/amd64 integration
