name: lint all
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: generate
        run: go generate ./...

      - name: run linter
        run: docker run -v $(pwd):/app -w /app golangci/golangci-lint:v1.31.0-alpine golangci-lint run ./... -v --enable "gofmt,golint,scopelint,gocritic"
