name: lint all
on:
  push:
    branches:
      - main
  pull_request:
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go lint.yml"

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.17, 1.16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-

      - name: download
        run: go mod download

      - name: generate
        run: go generate ./...

      - name: install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.31.0

      - name: run linter
        run: ./bin/golangci-lint run ./... --timeout "5m0s" --enable "gofmt,golint,scopelint,gocritic"
