name: integration test all
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: integration
        run: .github/workflows/integration.sh
