name: integration test all
on: push
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: integration
        run: |
          docker network create integration-bridge
          docker run --network integration-bridge --name localhost -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres
          cd integration/
          go run github.com/prisma/photongo lift save --create-db --name init
          go run github.com/prisma/photongo lift up
          cd ..
          docker build . -f docker/integration.dockerfile -t integration
          docker run --network integration-bridge integration
          docker stop postgres
