name: lint all
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: run linter
        run: docker build . -f docker/lint.dockerfile
