name: integration test all
on: push
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: integration
        run: .github/workflows/integration.sh
