name: test all
on:
  push:
    branches:
      - main
  pull_request:
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go test.yml"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.17, 1.16]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-

      - name: download
        run: go mod download -x

      - name: generate
        run: go generate ./...

      - name: setup
        run: go run ./test/setup/init setup

      - name: test
        run: go test ./... -v
